import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 22,
    paddingTop: 18,
    paddingBottom: 220,
    gap: 18,
  },
  heroCard: {
    borderWidth: 1,
    borderRadius: 30,
    padding: 20,
    gap: 12,
  },
  heroAccent: {
    width: 72,
    height: 6,
    borderRadius: 999,
  },
  kicker: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  title: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '900',
  },
  subtitle: {
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '600',
  },
  heroShopCard: {
    borderWidth: 1,
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 16,
    gap: 7,
  },
  heroShopLabel: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  heroShopValue: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '900',
  },
  segmentRow: {
    flexDirection: 'row',
    gap: 10,
  },
  segmentButton: {
    flex: 1,
    minHeight: 64,
    borderRadius: 22,
    borderWidth: 1,
    paddingHorizontal: 18,
    justifyContent: 'center',
  },
  segmentTitle: {
    fontSize: 18,
    fontWeight: '900',
  },
  segmentSubtitle: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  panel: {
    position: 'relative',
    overflow: 'hidden',
    borderWidth: 1,
    borderRadius: 30,
    paddingHorizontal: 22,
    paddingVertical: 20,
    gap: 18,
  },
  modeAccentLine: {
    position: 'absolute',
    top: 0,
    left: 22,
    right: 22,
    height: 3,
    borderBottomLeftRadius: 999,
    borderBottomRightRadius: 999,
  },
  panelHeader: {
    gap: 8,
  },
  panelKicker: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
  },
  panelTitle: {
    fontSize: 19,
    lineHeight: 25,
    fontWeight: '900',
  },
  fieldGroup: {
    gap: 9,
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  input: {
    minHeight: 56,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 16,
    fontSize: 18,
    fontWeight: '700',
  },
  helper: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
  },
  ctaButton: {
    minHeight: 60,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  ctaButtonDisabled: {
    opacity: 1,
  },
  ctaButtonText: {
    fontSize: 18,
    fontWeight: '900',
  },
  secondaryButton: {
    minHeight: 54,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  secondaryButtonText: {
    fontSize: 17,
    fontWeight: '800',
  },
  feedbackCard: {
    borderWidth: 1,
    borderRadius: 22,
    padding: 16,
    gap: 8,
  },
  feedbackTitle: {
    fontSize: 15,
    fontWeight: '900',
  },
  feedbackText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  lockOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 26,
    zIndex: 20,
  },
  lockBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  lockTint: {
    ...StyleSheet.absoluteFillObject,
  },
  lockCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 28,
    borderWidth: 1,
    paddingHorizontal: 22,
    paddingVertical: 24,
    alignItems: 'center',
    gap: 12,
  },
  lockIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 20,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lockIconText: {
    fontSize: 24,
    lineHeight: 24,
    fontWeight: '900',
  },
  lockTitle: {
    fontSize: 20,
    lineHeight: 25,
    fontWeight: '900',
    textAlign: 'center',
  },
  lockText: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '600',
    textAlign: 'center',
  },
})
