import { StyleSheet } from 'react-native'
import {
  type AndroidContrastMode,
  getAndroidCompanyPalette,
  getAndroidThemePalette,
  type AndroidThemePalette,
} from '../theme/androidDynamicColors'

function createStyles(palette: AndroidThemePalette, isDark: boolean) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: palette.background,
    },
    content: {
      paddingHorizontal: 18,
      paddingTop: 14,
      paddingBottom: 184,
      gap: 20,
    },
    card: {
      backgroundColor: palette.surfaceRaised,
      borderWidth: 1,
      borderColor: palette.outline,
      borderRadius: 32,
      paddingHorizontal: 20,
      paddingVertical: 20,
      gap: 12,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: isDark ? 0.24 : 0.07,
      shadowRadius: 24,
      elevation: 6,
    },
    greetingBlock: {
      backgroundColor: palette.primaryContainer,
      borderRadius: 30,
      borderWidth: 1,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
      paddingHorizontal: 18,
      paddingVertical: 18,
      gap: 12,
    },
    headerRow: {
      paddingHorizontal: 2,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 2,
    },
    compactHeaderOverlay: {
      position: 'absolute',
      top: 6,
      left: 18,
      right: 18,
      zIndex: 3,
    },
    compactHeaderCard: {
      minHeight: 34,
      borderRadius: 999,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
      backgroundColor: isDark ? 'rgba(20,30,45,0.92)' : 'rgba(255,255,255,0.90)',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    compactHeaderValue: {
      color: palette.onSurface,
      fontSize: 12,
      fontWeight: '800',
      lineHeight: 16,
    },
    compactHeaderDot: {
      width: 4,
      height: 4,
      borderRadius: 2,
      backgroundColor: palette.primaryStrong,
    },
    compactHeaderStatus: {
      color: palette.onSurfaceMuted,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 16,
    },
    balanceFlashCard: {
      flex: 1,
      backgroundColor: palette.surfaceRaised,
      borderWidth: 1,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
      borderRadius: 24,
      paddingHorizontal: 14,
      paddingVertical: 4,
      minHeight: 68,
      marginRight: 10,
    },
    balanceFlashCardActive: {
      borderColor: palette.primary,
      shadowColor: '#000000',
      shadowOpacity: isDark ? 0.18 : 0.05,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 5,
    },
    balanceFlashHeader: {
      position: 'relative',
      flexDirection: 'row',
      minHeight: 52,
      alignItems: 'center',
    },
    balanceFlashIconCircle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: palette.primaryContainerStrong,
      borderWidth: 1,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: isDark ? 0.16 : 0.04,
      shadowRadius: 12,
      elevation: 3,
    },
    balanceFlashIconText: {
      color: palette.primaryStrong,
      fontSize: 15,
      fontWeight: '900',
      lineHeight: 18,
      letterSpacing: -0.3,
    },
    balanceFlashCaption: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 16,
      includeFontPadding: false,
      marginTop: -1,
      marginBottom: 0,
    },
    balanceFlashCaptionInline: {
      color: palette.onSurfaceMuted,
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 18,
      includeFontPadding: false,
    },
    balanceFlashInlineRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    balanceFlashValue: {
      color: palette.onSurface,
      fontSize: 34,
      fontWeight: '800',
      lineHeight: 36,
    },
    balanceFlashValueInline: {
      color: palette.onSurface,
      fontSize: 20,
      fontWeight: '800',
      lineHeight: 22,
      fontVariant: ['tabular-nums'],
      includeFontPadding: false,
      marginTop: 0,
    },
    balanceFlashTextBlock: {
      flex: 1,
      minWidth: 0,
      marginLeft: 8,
      alignItems: 'flex-start',
      justifyContent: 'center',
      paddingRight: 34,
      minHeight: 52,
      paddingTop: 1,
    },
    balanceFlashChevron: {
      color: palette.onSurfaceMuted,
      fontSize: 16,
      fontWeight: '700',
      lineHeight: 18,
      position: 'absolute',
      right: 0,
      top: '50%',
      marginTop: -9,
    },
    balanceFlashHistory: {
      marginTop: 10,
      borderTopWidth: 1,
      borderTopColor: palette.outline,
      paddingTop: 8,
      gap: 8,
    },
    balanceFlashMuted: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    balanceHistoryRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    balanceHistoryTextBlock: {
      flex: 1,
    },
    balanceHistoryReason: {
      color: palette.onSurface,
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 17,
    },
    balanceHistoryDate: {
      color: palette.onSurfaceMuted,
      fontSize: 11,
      lineHeight: 14,
      marginTop: 2,
    },
    balanceHistoryPoints: {
      color: palette.primary,
      fontSize: 13,
      fontWeight: '800',
      lineHeight: 17,
      marginTop: 1,
    },
    headerAvatarButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: '#151515',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerAvatarText: {
      color: '#FFFFFF',
      fontSize: 18,
      fontWeight: '900',
    },
    scheduleSection: {
      gap: 12,
    },
    scheduleList: {
      paddingHorizontal: 4,
      gap: 10,
      paddingRight: 12,
    },
    scheduleCard: {
      width: 180,
      minHeight: 196,
      borderRadius: 30,
      borderWidth: 1,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
      backgroundColor: palette.surfaceRaised,
      overflow: 'hidden',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: isDark ? 0.16 : 0.06,
      shadowRadius: 18,
      elevation: 5,
    },
    scheduleCardTop: {
      backgroundColor: isDark ? palette.surfaceAccent : palette.primaryContainerStrong,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? palette.outline : palette.outlineVariant,
    },
    scheduleCardBody: {
      paddingHorizontal: 14,
      paddingVertical: 13,
      gap: 6,
    },
    scheduleDate: {
      color: palette.onSurface,
      fontSize: 22,
      fontWeight: '800',
      lineHeight: 28,
    },
    scheduleWeekday: {
      color: palette.onSurfaceMuted,
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 18,
    },
    scheduleTime: {
      color: palette.primaryStrong,
      fontSize: 14,
      fontWeight: '800',
      lineHeight: 20,
      marginTop: 4,
    },
    scheduleShop: {
      color: isDark ? palette.onSurface : palette.onSurface,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
      marginTop: 4,
    },
    scheduleAddress: {
      color: isDark ? palette.onSurface : palette.onSurfaceMuted,
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 18,
      marginTop: 2,
    },
    scheduleDutyBadge: {
      alignSelf: 'flex-start',
      marginTop: 8,
      borderRadius: 999,
      backgroundColor: palette.primaryContainer,
      borderWidth: 1,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    scheduleDutyText: {
      color: palette.primaryStrong,
      fontSize: 12,
      fontWeight: '700',
    },
    scheduleDutyValue: {
      color: palette.primary,
      fontSize: 22,
      fontWeight: '800',
      lineHeight: 26,
      marginTop: 8,
    },
    todayShiftSection: {
      gap: 12,
    },
    salarySection: {
      gap: 12,
    },
    salaryCard: {
      backgroundColor: palette.surfaceRaised,
      borderWidth: 1,
      borderColor: palette.outline,
      borderRadius: 28,
      overflow: 'hidden',
      paddingHorizontal: 18,
      paddingTop: 18,
      paddingBottom: 18,
      gap: 14,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: isDark ? 0.18 : 0.05,
      shadowRadius: 22,
      elevation: 6,
    },
    salaryCardLoaderOverlay: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      zIndex: 2,
      backgroundColor: 'rgba(0, 0, 0, 0.16)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    salaryCardContentLoading: {
      opacity: 0.42,
    },
    salaryLoadingState: {
      minHeight: 168,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
    },
    salaryLoadingText: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      fontWeight: '600',
      textAlign: 'center',
    },
    salaryCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    salaryPeriodSwitch: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
    },
    salaryPeriodTab: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette.outline,
      backgroundColor: palette.secondaryButton,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    salaryPeriodTabActive: {
      backgroundColor: palette.primaryContainer,
      borderColor: palette.primaryContainerStrong,
    },
    salaryPeriodTabText: {
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.2,
    },
    salaryPeriodTabTextActive: {
      color: palette.primaryStrong,
    },
    salaryPeriodTabTextInactive: {
      color: palette.onSurfaceMuted,
    },
    salaryBadge: {
      alignSelf: 'flex-start',
      borderRadius: 999,
      backgroundColor: palette.primaryContainer,
      borderWidth: 1,
      borderColor: palette.primaryContainerStrong,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    salaryBadgeText: {
      color: palette.primaryStrong,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.3,
      textTransform: 'uppercase',
    },
    salaryZoneText: {
      color: palette.primary,
      fontSize: 13,
      fontWeight: '800',
      lineHeight: 20,
    },
    salaryZoneBadge: {
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 10,
      paddingVertical: 4,
      alignSelf: 'flex-start',
    },
    salaryValue: {
      color: palette.onSurface,
      fontSize: 28,
      fontWeight: '800',
      lineHeight: 34,
      fontVariant: ['tabular-nums'],
    },
    salaryCaption: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    salarySummaryContent: {
      gap: 12,
    },
    salarySummaryContentCollapsed: {
      minHeight: 148,
      justifyContent: 'center',
    },
    salaryMetaRow: {
      marginTop: 2,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: palette.outline,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    salaryMetaInfo: {
      flex: 1,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    salaryMetaText: {
      color: palette.onSurface,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
      fontVariant: ['tabular-nums'],
    },
    salaryExpandButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: palette.surfaceAccent,
      borderWidth: 1,
      borderColor: palette.outline,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    salaryDetailsWrap: {
      overflow: 'hidden',
    },
    salaryExpandFooter: {
      marginTop: 4,
      alignSelf: 'flex-end',
    },
    salaryDetails: {
      marginTop: 12,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: palette.outline,
      gap: 14,
    },
    salaryZoneList: {
      gap: 8,
    },
    salaryZoneRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    salaryZoneRowLabel: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    salaryZoneRowValue: {
      color: palette.onSurface,
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 18,
      fontVariant: ['tabular-nums'],
    },
    salaryDetailsSection: {
      gap: 8,
    },
    salaryDetailsTitle: {
      color: palette.onSurface,
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 18,
    },
    salaryShiftRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
    },
    salaryShiftComparisonCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.outline,
      backgroundColor: palette.surface,
      paddingHorizontal: 12,
      paddingVertical: 12,
      gap: 10,
    },
    salaryShiftSummaryLine: {
      color: palette.onSurface,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
    },
    salaryShiftSummaryCaption: {
      color: palette.onSurfaceMuted,
      fontSize: 12,
      lineHeight: 16,
      marginTop: -2,
    },
    salaryShiftComparisonList: {
      gap: 6,
    },
    salaryShiftComparisonRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    salaryShiftComparisonLabel: {
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 16,
    },
    salaryShiftComparisonLabelGreen: {
      color: '#45C46B',
    },
    salaryShiftComparisonLabelBlue: {
      color: '#58A6FF',
    },
    salaryShiftComparisonLabelRed: {
      color: '#FF5A5F',
    },
    salaryShiftTextBlock: {
      flex: 1,
      gap: 2,
    },
    salaryFineTextBlock: {
      flex: 1,
      gap: 4,
    },
    salaryFineTitle: {
      color: palette.onSurface,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
    },
    salaryFineReason: {
      color: palette.onSurfaceMuted,
      fontSize: 12,
      lineHeight: 16,
    },
    salaryShiftShop: {
      color: palette.onSurface,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
      flex: 1,
    },
    salaryShiftDate: {
      color: palette.onSurfaceMuted,
      fontSize: 12,
      lineHeight: 16,
    },
    salaryShiftReason: {
      color: palette.onSurfaceMuted,
      fontSize: 12,
      lineHeight: 16,
    },
    salaryShiftValue: {
      color: palette.onSurface,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
      fontVariant: ['tabular-nums'],
    },
    salaryShiftValueBonus: {
      color: '#45C46B',
    },
    salaryShiftValuePenalty: {
      color: '#FF7A7A',
    },
    salaryEmptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      gap: 10,
    },
    salaryEmptyIcon: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: palette.primaryContainer,
      borderWidth: 1,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
      alignItems: 'center',
      justifyContent: 'center',
    },
    salaryEmptyIconText: {
      color: palette.primaryStrong,
      fontSize: 16,
      fontWeight: '800',
      lineHeight: 18,
    },
    salaryEmptyIconImage: {
      width: 24,
      height: 24,
      resizeMode: 'contain',
      tintColor: palette.primaryStrong,
    },
    salaryEmptyTitle: {
      color: palette.onSurface,
      fontSize: 16,
      fontWeight: '700',
      lineHeight: 22,
      textAlign: 'center',
    },
    salaryEmptyText: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      lineHeight: 18,
      textAlign: 'center',
    },
    todayShiftList: {
      gap: 10,
      paddingHorizontal: 4,
    },
    todayShiftCard: {
      borderRadius: 28,
      borderWidth: 1,
      borderColor: palette.outline,
      backgroundColor: palette.surfaceRaised,
      paddingHorizontal: 18,
      paddingVertical: 18,
      gap: 14,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: isDark ? 0.16 : 0.05,
      shadowRadius: 22,
      elevation: 6,
    },
    todayShiftTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    todayShiftBadge: {
      alignSelf: 'flex-start',
      borderRadius: 999,
      backgroundColor: palette.primaryContainer,
      borderWidth: 1,
      borderColor: palette.primaryContainerStrong,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    todayShiftBadgeText: {
      color: palette.primaryStrong,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.3,
      textTransform: 'uppercase',
    },
    todayShiftShop: {
      color: palette.onSurface,
      fontSize: 19,
      fontWeight: '800',
      lineHeight: 24,
      marginTop: 2,
    },
    todayShiftHours: {
      color: palette.primary,
      fontSize: 13,
      fontWeight: '800',
      lineHeight: 20,
    },
    todayShiftEmployeeBlock: {
      marginTop: 8,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: palette.outline,
      gap: 8,
    },
    todayShiftEmployeeList: {
      flexDirection: 'column',
      gap: 10,
    },
    todayShiftEmployeeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      minHeight: 40,
    },
    todayShiftEmployeePill: {
      borderRadius: 999,
      backgroundColor: palette.surfaceAccent,
      borderWidth: 1,
      borderColor: palette.outline,
      minHeight: 34,
      paddingHorizontal: 11,
      paddingVertical: 7,
      justifyContent: 'center',
    },
    todayShiftEmployeeName: {
      color: palette.onSurface,
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 18,
    },
    todayShiftCallButton: {
      borderRadius: 999,
      backgroundColor: palette.surfaceAccent,
      borderWidth: 1,
      borderColor: palette.outline,
      minHeight: 34,
      paddingHorizontal: 13,
      paddingVertical: 7,
      justifyContent: 'center',
    },
    todayShiftCallButtonText: {
      color: palette.primaryStrong,
      fontSize: 12,
      fontWeight: '800',
      lineHeight: 16,
    },
    todayShiftEmptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 8,
      gap: 10,
    },
    todayShiftEmptyIcon: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: palette.primaryContainer,
      borderWidth: 1,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
      alignItems: 'center',
      justifyContent: 'center',
    },
    todayShiftEmptyIconText: {
      color: palette.primaryStrong,
      fontSize: 18,
      fontWeight: '800',
      lineHeight: 20,
    },
    todayShiftEmptyIconImage: {
      width: 24,
      height: 24,
      resizeMode: 'contain',
      tintColor: palette.primaryStrong,
    },
    todayShiftEmptyTitle: {
      color: palette.onSurface,
      fontSize: 15,
      fontWeight: '700',
      lineHeight: 20,
      textAlign: 'center',
    },
    todayShiftEmptyText: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      lineHeight: 18,
      textAlign: 'center',
    },
    todayShiftExpandIconOpen: {
      transform: [{ rotate: '-90deg' }],
    },
    subtitle: {
      color: palette.onSurfaceMuted,
      fontSize: 14,
      lineHeight: 20,
    },
    sectionTitle: {
      color: palette.onSurface,
      fontSize: 22,
      fontWeight: '800',
      letterSpacing: -0.4,
    },
    badgeOpen: {
      alignSelf: 'flex-start',
      backgroundColor: palette.primaryContainer,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 7,
    },
    badgeClosed: {
      alignSelf: 'flex-start',
      backgroundColor: palette.closedBadge,
      borderColor: palette.closedBadgeBorder,
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 7,
    },
    badgeText: {
      color: palette.onSurface,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0.15,
    },
    shiftInlineLoading: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      minHeight: 28,
    },
    shiftInlineLoadingText: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    shiftFlashMessageError: {
      backgroundColor: isDark ? '#4A1914' : '#7F271F',
      borderColor: isDark ? '#A14A40' : '#A33D32',
    },
    shiftFlashMessageSuccess: {
      backgroundColor: isDark ? '#1A3027' : '#D4EBDD',
      borderColor: isDark ? '#3E7560' : '#7EA88F',
    },
    shiftFlashMessageWarning: {
      backgroundColor: isDark ? '#3A270F' : '#EED6B6',
      borderColor: isDark ? '#9A6A2C' : '#B8823E',
    },
    shiftFlashTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
      minWidth: 0,
    },
    shiftFlashBadge: {
      width: 24,
      height: 24,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.28)' : 'rgba(19,35,27,0.2)',
      backgroundColor: isDark ? 'rgba(255,255,255,0.12)' : 'rgba(19,35,27,0.06)',
    },
    shiftFlashBadgeError: {
      backgroundColor: isDark ? '#BE4D40' : '#C25A4E',
      borderColor: 'rgba(255,255,255,0.35)',
    },
    shiftFlashIconCircleSuccess: {
      backgroundColor: isDark ? '#3F7F66' : '#5E9F83',
    },
    shiftFlashIconCircleError: {
      backgroundColor: isDark ? '#E86152' : '#D84C3E',
    },
    shiftFlashIconCircleWarning: {
      backgroundColor: isDark ? '#C78A38' : '#B87823',
    },
    shiftFlashIconText: {
      color: '#FFFFFF',
      fontSize: 18,
      fontWeight: '800',
      lineHeight: 20,
    },
    shiftFlashMessageText: {
      color: isDark ? '#FFFFFF' : '#13231B',
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 19,
      paddingLeft: 2,
    },
    shiftFlashTitle: {
      color: isDark ? '#FFFFFF' : '#13231B',
      fontSize: 15,
      fontWeight: '900',
      lineHeight: 20,
      letterSpacing: 0.2,
      flex: 1,
    },
    shiftFlashBadgeText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: '900',
      lineHeight: 14,
      textAlign: 'center',
    },
    shiftFlashHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    shiftFlashCloseButton: {
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.2)' : 'rgba(19,35,27,0.14)',
      backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : 'rgba(19,35,27,0.05)',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 0,
    },
    shiftFlashCloseText: {
      color: isDark ? '#FFFFFF' : '#13231B',
      fontSize: 16,
      fontWeight: '800',
      lineHeight: 18,
    },
    button: {
      backgroundColor: palette.primary,
      borderRadius: 22,
      minHeight: 50,
      paddingVertical: 13,
      paddingHorizontal: 18,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'transparent',
    },
    buttonSecondary: {
      backgroundColor: palette.secondaryButton,
      borderWidth: 1,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
    },
    buttonDisabled: {
      opacity: 1,
      backgroundColor: palette.surfaceMuted,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
    },
    buttonText: {
      color: palette.buttonText,
      fontSize: 15,
      fontWeight: '800',
      lineHeight: 20,
      letterSpacing: 0.15,
      textAlign: 'center',
      includeFontPadding: false,
    },
    buttonTextSecondary: {
      color: palette.onSurface,
    },
    buttonTextDisabled: {
      color: palette.onSurfaceMuted,
    },
    buttonTextDanger: {
      color: '#FFFFFF',
    },
    flowPrimaryButton: {
      marginTop: 12,
    },
    closeDecisionGroup: {
      marginTop: 12,
    },
    closeDecisionPrimaryButton: {
      marginBottom: 12,
    },
    closeDecisionDangerButton: {
      marginTop: 0,
      backgroundColor: isDark ? '#4A2C2C' : '#F6D5D1',
      borderWidth: 1,
      borderColor: isDark ? '#8A4E4E' : '#D49C95',
    },
    closeDecisionButtonText: {
      color: isDark ? '#FFFFFF' : '#2B1A1A',
    },
    shiftProgressContainer: {
      marginTop: 10,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
      backgroundColor: isDark ? palette.surfaceRaised : palette.surfaceAccent,
      paddingHorizontal: 12,
      paddingVertical: 10,
      gap: 6,
    },
    shiftProgressHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    shiftProgressLabel: {
      color: palette.onSurfaceMuted,
      fontSize: 11,
      lineHeight: 14,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    shiftProgressValue: {
      color: palette.onSurface,
      fontSize: 14,
      lineHeight: 18,
      fontWeight: '800',
    },
    shiftProgressTrack: {
      marginTop: 2,
      height: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
      backgroundColor: isDark ? '#111622' : '#DEE7F3',
      overflow: 'hidden',
    },
    shiftProgressFill: {
      height: '100%',
      borderRadius: 999,
      backgroundColor: palette.primaryStrong,
    },
    shiftProgressMeta: {
      color: palette.onSurfaceMuted,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '600',
    },
    smallText: {
      color: isDark ? '#D2DAE2' : palette.onSurfaceMuted,
      fontSize: 12,
      lineHeight: 18,
    },
    input: {
      backgroundColor: palette.surface,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      borderRadius: 18,
      color: palette.onSurface,
      paddingHorizontal: 14,
      paddingVertical: 13,
      fontSize: 16,
      fontWeight: '700',
    },
    inputFocused: {
      borderColor: palette.primary,
      shadowColor: '#000000',
      shadowOpacity: isDark ? 0.14 : 0.05,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 6 },
      elevation: 4,
    },
    partnerLossCard: {
      marginTop: 18,
      gap: 12,
      paddingTop: 14,
      borderTopWidth: 1,
      borderTopColor: isDark ? palette.outline : palette.outlineVariant,
    },
    partnerLossHeader: {
      gap: 6,
    },
    certificatesShortcutButton: {
      alignSelf: 'flex-start',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: isDark ? palette.primaryContainerStrong : palette.outline,
      backgroundColor: isDark ? palette.primaryContainer : palette.surfaceAccent,
      paddingHorizontal: 12,
      paddingVertical: 8,
      marginBottom: 2,
    },
    certificatesShortcutButtonText: {
      color: palette.primaryStrong,
      fontSize: 13,
      fontWeight: '800',
      lineHeight: 17,
      letterSpacing: 0.2,
    },
    certificatesBottomCapsule: {
      marginTop: 8,
      backgroundColor: palette.surfaceMuted,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
    },
    partnerLossKicker: {
      color: palette.primaryStrong,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0.4,
      textTransform: 'uppercase',
    },
    partnerLossTitle: {
      color: palette.onSurface,
      fontSize: 17,
      fontWeight: '800',
      lineHeight: 22,
      letterSpacing: -0.2,
    },
    partnerLossInput: {
      minHeight: 104,
      borderRadius: 18,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      lineHeight: 21,
      fontWeight: '600',
    },
    partnerLossInputDisabled: {
      opacity: 1,
      backgroundColor: palette.surfaceMuted,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
      color: palette.onSurfaceMuted,
    },
    partnerLossFeedback: {
      borderRadius: 18,
      borderWidth: 1,
      paddingHorizontal: 14,
      paddingVertical: 12,
      gap: 4,
    },
    partnerLossErrorCard: {
      backgroundColor: palette.errorContainer,
      borderColor: palette.errorBorder,
    },
    partnerLossSuccessCard: {
      backgroundColor: palette.successContainer,
      borderColor: palette.successBorder,
    },
    partnerLossFeedbackTitle: {
      color: palette.onSurface,
      fontSize: 13,
      fontWeight: '800',
      lineHeight: 17,
    },
    partnerLossFeedbackText: {
      color: palette.onSurface,
      fontSize: 14,
      lineHeight: 19,
      fontWeight: '500',
    },
    partnerLossSubmitButton: {
      marginTop: 2,
    },
    sealNumberBox: {
      backgroundColor: palette.surface,
      borderWidth: 1,
      borderColor: palette.primary,
      borderRadius: 18,
      paddingHorizontal: 14,
      paddingVertical: 13,
    },
    sealNumberValue: {
      color: palette.onSurface,
      fontSize: 20,
      fontWeight: '900',
      letterSpacing: 1.4,
    },
    reviewEditButton: {
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      backgroundColor: palette.secondaryButton,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    reviewEditButtonText: {
      color: palette.primaryStrong,
      fontSize: 12,
      fontWeight: '800',
    },
    photoPreview: {
      width: '100%',
      height: 220,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    keyboardAccessory: {
      backgroundColor: palette.surfaceRaised,
      borderTopWidth: 1,
      borderTopColor: isDark ? palette.outline : palette.outlineVariant,
      paddingHorizontal: 12,
      paddingVertical: 8,
      alignItems: 'flex-end',
    },
    keyboardAccessoryButton: {
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    keyboardAccessoryText: {
      color: palette.primaryStrong,
      fontSize: 16,
      fontWeight: '800',
    },
    shopModalOverlay: {
      flex: 1,
      backgroundColor: isDark ? 'rgba(2,6,10,0.7)' : 'rgba(16,22,30,0.32)',
      justifyContent: 'center',
      paddingHorizontal: 20,
      paddingVertical: 24,
    },
    shopModalCard: {
      backgroundColor: palette.surfaceRaised,
      borderWidth: 1,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
      borderRadius: 30,
      overflow: 'hidden',
      maxHeight: 460,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 20 },
      shadowOpacity: isDark ? 0.28 : 0.1,
      shadowRadius: 34,
      elevation: 14,
    },
    shopModalTitle: {
      color: palette.onSurface,
      fontSize: 19,
      fontWeight: '800',
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 12,
    },
    shopDropdownScroll: {
      maxHeight: 360,
      paddingHorizontal: 12,
      paddingBottom: 12,
    },
    shopOptionRow: {
      minHeight: 58,
      paddingHorizontal: 16,
      marginBottom: 8,
      borderRadius: 18,
      justifyContent: 'center',
      backgroundColor: palette.surface,
      borderWidth: 1,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
    },
    shopOptionRowActive: {
      backgroundColor: palette.primaryContainer,
      borderColor: palette.primary,
    },
    shopOptionText: {
      color: palette.onSurface,
      fontSize: 15,
      fontWeight: '600',
    },
    shopOptionTextActive: {
      color: palette.primaryStrong,
      fontWeight: '700',
    },
    shopEmptyWrap: {
      paddingHorizontal: 16,
      paddingVertical: 18,
      gap: 12,
    },
    shopEmptyText: {
      color: isDark ? '#C0C9D1' : palette.onSurfaceMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    shopRefreshButton: {
      alignSelf: 'flex-start',
      paddingHorizontal: 14,
    },
    shopSelectTrigger: {
      minHeight: 60,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: isDark ? palette.outline : palette.outlineVariant,
      backgroundColor: palette.surfaceRaised,
      paddingHorizontal: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: isDark ? 0.14 : 0.04,
      shadowRadius: 18,
      elevation: 4,
    },
    shopSelectTriggerActive: {
      borderColor: palette.primary,
      backgroundColor: palette.surfaceAccent,
    },
    shopSelectTriggerText: {
      color: isDark ? '#C0C9D1' : palette.onSurfaceMuted,
      fontSize: 15,
      fontWeight: '600',
    },
    shopSelectTriggerTextActive: {
      color: palette.onSurface,
      fontWeight: '700',
    },
    shopSelectChevron: {
      color: palette.primaryStrong,
      fontSize: 16,
      lineHeight: 18,
      fontWeight: '800',
    },
  })
}

const stylesCache = new Map<string, ReturnType<typeof createStyles>>()

export function getAndroidShiftStyles(
  themeMode: 'company' | 'material',
  isDark: boolean,
  contrastMode: AndroidContrastMode = 'balanced',
) {
  const key = `${themeMode}:${isDark ? 'dark' : 'light'}:${contrastMode}`
  const cached = stylesCache.get(key)
  if (cached) {
    return cached
  }

  const styles = createStyles(
    themeMode === 'company' ? getAndroidCompanyPalette() : getAndroidThemePalette(isDark, contrastMode),
    themeMode === 'company' ? true : isDark,
  )
  stylesCache.set(key, styles)
  return styles
}

export const lightStyles = createStyles(getAndroidThemePalette(false), false)
export const darkStyles = createStyles(getAndroidThemePalette(true), true)
export const companyStyles = createStyles(getAndroidCompanyPalette(), true)
