import { StyleSheet } from 'react-native'
import {
  getAndroidCompanyPalette,
  getAndroidThemePalette,
  type AndroidThemePalette,
} from '../theme/androidDynamicColors'

function createStyles(palette: AndroidThemePalette, isDark: boolean) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: palette.background,
    },
    content: {
      paddingHorizontal: 18,
      paddingTop: 14,
      paddingBottom: 132,
      gap: 16,
    },
    card: {
      backgroundColor: palette.surfaceRaised,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      borderRadius: 32,
      paddingHorizontal: 20,
      paddingVertical: 20,
      gap: 12,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: isDark ? 0.24 : 0.07,
      shadowRadius: 24,
      elevation: 6,
    },
    greetingBlock: {
      backgroundColor: palette.primaryContainer,
      borderRadius: 30,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      paddingHorizontal: 18,
      paddingVertical: 18,
      gap: 12,
    },
    headerRow: {
      paddingHorizontal: 2,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 2,
    },
    balanceFlashCard: {
      flex: 1,
      backgroundColor: palette.surfaceRaised,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      borderRadius: 28,
      paddingHorizontal: 16,
      paddingVertical: 14,
      marginRight: 10,
    },
    balanceFlashCardActive: {
      borderColor: palette.primary,
      shadowColor: '#000000',
      shadowOpacity: isDark ? 0.18 : 0.05,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 5,
    },
    balanceFlashIconCircle: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: palette.primaryContainerStrong,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      alignItems: 'center',
      justifyContent: 'center',
    },
    balanceFlashCaption: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 16,
    },
    balanceFlashValue: {
      color: palette.onSurface,
      fontSize: 24,
      fontWeight: '800',
      lineHeight: 30,
    },
    balanceFlashChevron: {
      color: palette.onSurfaceMuted,
      fontSize: 20,
      fontWeight: '700',
      lineHeight: 22,
      marginLeft: 8,
    },
    balanceFlashHistory: {
      marginTop: 10,
      borderTopWidth: 1,
      borderTopColor: palette.outlineVariant,
      paddingTop: 8,
      gap: 8,
    },
    balanceFlashMuted: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    balanceHistoryRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    balanceHistoryTextBlock: {
      flex: 1,
    },
    balanceHistoryReason: {
      color: palette.onSurface,
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 17,
    },
    balanceHistoryDate: {
      color: palette.onSurfaceMuted,
      fontSize: 11,
      lineHeight: 14,
      marginTop: 2,
    },
    balanceHistoryPoints: {
      color: palette.primary,
      fontSize: 13,
      fontWeight: '800',
      lineHeight: 17,
      marginTop: 1,
    },
    headerAvatarButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: palette.primaryContainerStrong,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerAvatarText: {
      color: palette.primaryStrong,
      fontSize: 18,
      fontWeight: '900',
    },
    scheduleSection: {
      gap: 12,
    },
    scheduleList: {
      paddingHorizontal: 4,
      gap: 10,
      paddingRight: 12,
    },
    scheduleCard: {
      width: 172,
      minHeight: 196,
      borderRadius: 28,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      backgroundColor: palette.surfaceRaised,
      overflow: 'hidden',
    },
    scheduleCardTop: {
      backgroundColor: palette.primaryContainerStrong,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    scheduleCardBody: {
      paddingHorizontal: 14,
      paddingVertical: 12,
      gap: 5,
    },
    scheduleDate: {
      color: palette.onSurface,
      fontSize: 22,
      fontWeight: '800',
      lineHeight: 28,
    },
    scheduleWeekday: {
      color: palette.primaryStrong,
      fontSize: 14,
      fontWeight: '600',
      lineHeight: 18,
    },
    scheduleTime: {
      color: palette.primary,
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 20,
      marginTop: 4,
    },
    scheduleAddress: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 17,
      marginTop: 2,
    },
    scheduleDutyBadge: {
      alignSelf: 'flex-start',
      marginTop: 8,
      borderRadius: 999,
      backgroundColor: palette.primaryContainer,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    scheduleDutyText: {
      color: palette.primaryStrong,
      fontSize: 12,
      fontWeight: '700',
    },
    scheduleDutyValue: {
      color: palette.primary,
      fontSize: 22,
      fontWeight: '800',
      lineHeight: 26,
      marginTop: 8,
    },
    subtitle: {
      color: palette.onSurfaceMuted,
      fontSize: 14,
      lineHeight: 20,
    },
    sectionTitle: {
      color: palette.onSurface,
      fontSize: 22,
      fontWeight: '800',
      letterSpacing: -0.4,
    },
    badgeOpen: {
      alignSelf: 'flex-start',
      backgroundColor: palette.primaryContainer,
      borderColor: palette.outlineVariant,
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 7,
    },
    badgeClosed: {
      alignSelf: 'flex-start',
      backgroundColor: palette.closedBadge,
      borderColor: palette.closedBadgeBorder,
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 7,
    },
    badgeText: {
      color: palette.onSurface,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0.15,
    },
    button: {
      backgroundColor: palette.primary,
      borderRadius: 22,
      minHeight: 50,
      paddingVertical: 13,
      paddingHorizontal: 18,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'transparent',
    },
    buttonSecondary: {
      backgroundColor: palette.secondaryButton,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    buttonDisabled: {
      opacity: 0.5,
    },
    buttonText: {
      color: palette.buttonText,
      fontSize: 15,
      fontWeight: '800',
      letterSpacing: 0.15,
    },
    smallText: {
      color: palette.onSurfaceMuted,
      fontSize: 12,
      lineHeight: 18,
    },
    shopModalOverlay: {
      flex: 1,
      backgroundColor: isDark ? 'rgba(0,0,0,0.52)' : 'rgba(18,24,30,0.28)',
      justifyContent: 'center',
      paddingHorizontal: 20,
      paddingVertical: 24,
    },
    shopModalCard: {
      backgroundColor: palette.surfaceRaised,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      borderRadius: 24,
      overflow: 'hidden',
      maxHeight: 420,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 14 },
      shadowOpacity: isDark ? 0.22 : 0.08,
      shadowRadius: 24,
      elevation: 8,
    },
    shopModalTitle: {
      color: palette.onSurface,
      fontSize: 18,
      fontWeight: '800',
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 12,
    },
    shopDropdownScroll: {
      maxHeight: 344,
    },
    shopOptionRow: {
      minHeight: 54,
      paddingHorizontal: 16,
      justifyContent: 'center',
      borderBottomWidth: 1,
      borderBottomColor: palette.outlineVariant,
    },
    shopOptionRowActive: {
      backgroundColor: palette.primaryContainer,
    },
    shopOptionText: {
      color: palette.onSurface,
      fontSize: 15,
      fontWeight: '500',
    },
    shopOptionTextActive: {
      color: palette.primaryStrong,
      fontWeight: '700',
    },
    shopEmptyWrap: {
      paddingHorizontal: 16,
      paddingVertical: 18,
      gap: 12,
    },
    shopEmptyText: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    shopRefreshButton: {
      alignSelf: 'flex-start',
      paddingHorizontal: 14,
    },
    shopSelectTrigger: {
      minHeight: 54,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      backgroundColor: palette.surface,
      paddingHorizontal: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    shopSelectTriggerActive: {
      borderColor: palette.primary,
      backgroundColor: palette.primaryContainer,
    },
    shopSelectTriggerText: {
      color: palette.onSurfaceMuted,
      fontSize: 15,
      fontWeight: '500',
    },
    shopSelectTriggerTextActive: {
      color: palette.onSurface,
      fontWeight: '700',
    },
    shopSelectChevron: {
      color: palette.onSurface,
      fontSize: 15,
      lineHeight: 18,
    },
  })
}

export const lightStyles = createStyles(getAndroidThemePalette(false), false)
export const darkStyles = createStyles(getAndroidThemePalette(true), true)
export const companyStyles = createStyles(getAndroidCompanyPalette(), true)
