import { StyleSheet } from 'react-native'
import {
  getAndroidCompanyPalette,
  getAndroidThemePalette,
  type AndroidThemePalette,
} from '../theme/androidDynamicColors'

function createStyles(palette: AndroidThemePalette, isDark: boolean) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: palette.background,
    },
    content: {
      paddingHorizontal: 18,
      paddingTop: 14,
      paddingBottom: 132,
      gap: 20,
    },
    card: {
      backgroundColor: palette.surfaceRaised,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      borderRadius: 32,
      paddingHorizontal: 20,
      paddingVertical: 20,
      gap: 12,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: isDark ? 0.24 : 0.07,
      shadowRadius: 24,
      elevation: 6,
    },
    greetingBlock: {
      backgroundColor: palette.primaryContainer,
      borderRadius: 30,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      paddingHorizontal: 18,
      paddingVertical: 18,
      gap: 12,
    },
    headerRow: {
      paddingHorizontal: 2,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 2,
    },
    balanceFlashCard: {
      flex: 1,
      backgroundColor: palette.surfaceRaised,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      borderRadius: 28,
      paddingHorizontal: 16,
      paddingVertical: 14,
      marginRight: 10,
    },
    balanceFlashCardActive: {
      borderColor: palette.primary,
      shadowColor: '#000000',
      shadowOpacity: isDark ? 0.18 : 0.05,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 5,
    },
    balanceFlashIconCircle: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: palette.primaryContainerStrong,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      alignItems: 'center',
      justifyContent: 'center',
    },
    balanceFlashCaption: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 16,
    },
    balanceFlashValue: {
      color: palette.onSurface,
      fontSize: 24,
      fontWeight: '800',
      lineHeight: 30,
    },
    balanceFlashChevron: {
      color: palette.onSurfaceMuted,
      fontSize: 20,
      fontWeight: '700',
      lineHeight: 22,
      marginLeft: 8,
    },
    balanceFlashHistory: {
      marginTop: 10,
      borderTopWidth: 1,
      borderTopColor: palette.outlineVariant,
      paddingTop: 8,
      gap: 8,
    },
    balanceFlashMuted: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    balanceHistoryRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    balanceHistoryTextBlock: {
      flex: 1,
    },
    balanceHistoryReason: {
      color: palette.onSurface,
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 17,
    },
    balanceHistoryDate: {
      color: palette.onSurfaceMuted,
      fontSize: 11,
      lineHeight: 14,
      marginTop: 2,
    },
    balanceHistoryPoints: {
      color: palette.primary,
      fontSize: 13,
      fontWeight: '800',
      lineHeight: 17,
      marginTop: 1,
    },
    headerAvatarButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: palette.primaryContainerStrong,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerAvatarText: {
      color: palette.primaryStrong,
      fontSize: 18,
      fontWeight: '900',
    },
    scheduleSection: {
      gap: 12,
    },
    scheduleList: {
      paddingHorizontal: 4,
      gap: 10,
      paddingRight: 12,
    },
    scheduleCard: {
      width: 172,
      minHeight: 196,
      borderRadius: 28,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      backgroundColor: palette.surfaceRaised,
      overflow: 'hidden',
    },
    scheduleCardTop: {
      backgroundColor: palette.primaryContainerStrong,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    scheduleCardBody: {
      paddingHorizontal: 14,
      paddingVertical: 12,
      gap: 5,
    },
    scheduleDate: {
      color: palette.onSurface,
      fontSize: 22,
      fontWeight: '800',
      lineHeight: 28,
    },
    scheduleWeekday: {
      color: palette.primaryStrong,
      fontSize: 14,
      fontWeight: '600',
      lineHeight: 18,
    },
    scheduleTime: {
      color: palette.primary,
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 20,
      marginTop: 4,
    },
    scheduleAddress: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 17,
      marginTop: 2,
    },
    scheduleDutyBadge: {
      alignSelf: 'flex-start',
      marginTop: 8,
      borderRadius: 999,
      backgroundColor: palette.primaryContainer,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    scheduleDutyText: {
      color: palette.primaryStrong,
      fontSize: 12,
      fontWeight: '700',
    },
    scheduleDutyValue: {
      color: palette.primary,
      fontSize: 22,
      fontWeight: '800',
      lineHeight: 26,
      marginTop: 8,
    },
    todayShiftSection: {
      gap: 12,
    },
    salarySection: {
      gap: 12,
    },
    salaryCard: {
      backgroundColor: palette.surfaceRaised,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      borderRadius: 28,
      paddingHorizontal: 18,
      paddingTop: 18,
      paddingBottom: 18,
      gap: 14,
    },
    salaryCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    salaryPeriodSwitch: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
    },
    salaryPeriodTab: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      backgroundColor: palette.surfaceContainerHigh,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    salaryPeriodTabActive: {
      backgroundColor: palette.primaryContainer,
      borderColor: palette.outlineVariant,
    },
    salaryPeriodTabText: {
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.2,
    },
    salaryPeriodTabTextActive: {
      color: palette.primaryStrong,
    },
    salaryPeriodTabTextInactive: {
      color: palette.onSurfaceMuted,
    },
    salaryBadge: {
      alignSelf: 'flex-start',
      borderRadius: 999,
      backgroundColor: palette.primaryContainer,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    salaryBadgeText: {
      color: palette.primaryStrong,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.3,
      textTransform: 'uppercase',
    },
    salaryZoneText: {
      color: palette.primary,
      fontSize: 13,
      fontWeight: '800',
      lineHeight: 20,
    },
    salaryZoneBadge: {
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 10,
      paddingVertical: 4,
      alignSelf: 'flex-start',
    },
    salaryValue: {
      color: palette.onSurface,
      fontSize: 28,
      fontWeight: '800',
      lineHeight: 34,
      fontVariant: ['tabular-nums'],
    },
    salaryCaption: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    salaryMetaRow: {
      marginTop: 2,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: palette.outlineVariant,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    salaryMetaInfo: {
      flex: 1,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    salaryMetaText: {
      color: palette.onSurface,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
      fontVariant: ['tabular-nums'],
    },
    salaryExpandButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: palette.surfaceContainerHigh,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    salaryExpandIcon: {
      color: palette.primaryStrong,
      fontSize: 24,
      fontWeight: '800',
      lineHeight: 24,
      transform: [{ rotate: '90deg' }],
    },
    salaryExpandIconOpen: {
      transform: [{ rotate: '-90deg' }],
    },
    salaryDetailsWrap: {
      overflow: 'hidden',
    },
    salaryExpandFooter: {
      marginTop: 4,
      width: '100%',
      alignItems: 'flex-end',
      justifyContent: 'flex-end',
    },
    salaryDetails: {
      marginTop: 12,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: palette.outlineVariant,
      gap: 14,
    },
    salaryZoneList: {
      gap: 8,
    },
    salaryZoneRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    salaryZoneRowLabel: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    salaryZoneRowValue: {
      color: palette.onSurface,
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 18,
      fontVariant: ['tabular-nums'],
    },
    salaryDetailsSection: {
      gap: 8,
    },
    salaryDetailsTitle: {
      color: palette.onSurface,
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 18,
    },
    salaryShiftRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
    },
    salaryShiftComparisonCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      backgroundColor: palette.surfaceElevated,
      paddingHorizontal: 12,
      paddingVertical: 12,
      gap: 10,
    },
    salaryShiftSummaryLine: {
      color: palette.onSurface,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
    },
    salaryShiftSummaryCaption: {
      color: palette.onSurfaceMuted,
      fontSize: 12,
      lineHeight: 16,
      marginTop: -2,
    },
    salaryShiftComparisonList: {
      gap: 6,
    },
    salaryShiftComparisonRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    salaryShiftComparisonLabel: {
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 16,
    },
    salaryShiftComparisonLabelGreen: {
      color: '#45C46B',
    },
    salaryShiftComparisonLabelBlue: {
      color: '#58A6FF',
    },
    salaryShiftComparisonLabelRed: {
      color: '#FF5A5F',
    },
    salaryShiftTextBlock: {
      flex: 1,
      gap: 2,
    },
    salaryFineTextBlock: {
      flex: 1,
      gap: 4,
    },
    salaryFineTitle: {
      color: palette.onSurface,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
    },
    salaryFineReason: {
      color: palette.onSurfaceMuted,
      fontSize: 12,
      lineHeight: 16,
    },
    salaryShiftShop: {
      color: palette.onSurface,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
      flex: 1,
    },
    salaryShiftDate: {
      color: palette.onSurfaceMuted,
      fontSize: 12,
      lineHeight: 16,
    },
    salaryShiftReason: {
      color: palette.onSurfaceMuted,
      fontSize: 12,
      lineHeight: 16,
    },
    salaryShiftValue: {
      color: palette.onSurface,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
      fontVariant: ['tabular-nums'],
    },
    salaryShiftValueBonus: {
      color: '#45C46B',
    },
    salaryShiftValuePenalty: {
      color: '#FF7A7A',
    },
    salaryEmptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      gap: 10,
    },
    salaryEmptyIcon: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: palette.primaryContainer,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      alignItems: 'center',
      justifyContent: 'center',
    },
    salaryEmptyIconText: {
      color: palette.primaryStrong,
      fontSize: 16,
      fontWeight: '800',
      lineHeight: 18,
    },
    salaryEmptyIconImage: {
      width: 24,
      height: 24,
      resizeMode: 'contain',
      tintColor: palette.primaryStrong,
    },
    salaryEmptyTitle: {
      color: palette.onSurface,
      fontSize: 16,
      fontWeight: '700',
      lineHeight: 22,
      textAlign: 'center',
    },
    salaryEmptyText: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      lineHeight: 18,
      textAlign: 'center',
    },
    todayShiftList: {
      gap: 10,
      paddingHorizontal: 4,
    },
    todayShiftCard: {
      borderRadius: 28,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      backgroundColor: palette.surfaceRaised,
      paddingHorizontal: 18,
      paddingVertical: 18,
      gap: 14,
    },
    todayShiftTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    todayShiftBadge: {
      alignSelf: 'flex-start',
      borderRadius: 999,
      backgroundColor: palette.primaryContainer,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    todayShiftBadgeText: {
      color: palette.primaryStrong,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.3,
      textTransform: 'uppercase',
    },
    todayShiftShop: {
      color: palette.onSurface,
      fontSize: 19,
      fontWeight: '800',
      lineHeight: 24,
      marginTop: 2,
    },
    todayShiftHours: {
      color: palette.primary,
      fontSize: 13,
      fontWeight: '800',
      lineHeight: 20,
    },
    todayShiftEmployeeBlock: {
      marginTop: 8,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: palette.outlineVariant,
      gap: 8,
    },
    todayShiftEmployeeList: {
      flexDirection: 'column',
      gap: 10,
    },
    todayShiftEmployeeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      minHeight: 40,
    },
    todayShiftEmployeePill: {
      borderRadius: 999,
      backgroundColor: palette.primaryContainer,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      minHeight: 34,
      paddingHorizontal: 11,
      paddingVertical: 7,
      justifyContent: 'center',
    },
    todayShiftEmployeeName: {
      color: palette.onSurface,
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 18,
    },
    todayShiftCallButton: {
      borderRadius: 999,
      backgroundColor: palette.surfaceElevated,
      borderWidth: 1,
      borderColor: palette.outline,
      minHeight: 34,
      paddingHorizontal: 13,
      paddingVertical: 7,
      justifyContent: 'center',
    },
    todayShiftCallButtonText: {
      color: palette.primaryStrong,
      fontSize: 12,
      fontWeight: '800',
      lineHeight: 16,
    },
    todayShiftEmptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 8,
      gap: 10,
    },
    todayShiftEmptyIcon: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: palette.primaryContainer,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      alignItems: 'center',
      justifyContent: 'center',
    },
    todayShiftEmptyIconText: {
      color: palette.primaryStrong,
      fontSize: 18,
      fontWeight: '800',
      lineHeight: 20,
    },
    todayShiftEmptyIconImage: {
      width: 24,
      height: 24,
      resizeMode: 'contain',
      tintColor: palette.primaryStrong,
    },
    todayShiftEmptyTitle: {
      color: palette.onSurface,
      fontSize: 15,
      fontWeight: '700',
      lineHeight: 20,
      textAlign: 'center',
    },
    todayShiftEmptyText: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      lineHeight: 18,
      textAlign: 'center',
    },
    todayShiftExpandIconOpen: {
      transform: [{ rotate: '-90deg' }],
    },
    subtitle: {
      color: palette.onSurfaceMuted,
      fontSize: 14,
      lineHeight: 20,
    },
    sectionTitle: {
      color: palette.onSurface,
      fontSize: 22,
      fontWeight: '800',
      letterSpacing: -0.4,
    },
    badgeOpen: {
      alignSelf: 'flex-start',
      backgroundColor: palette.primaryContainer,
      borderColor: palette.outlineVariant,
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 7,
    },
    badgeClosed: {
      alignSelf: 'flex-start',
      backgroundColor: palette.closedBadge,
      borderColor: palette.closedBadgeBorder,
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 7,
    },
    badgeText: {
      color: palette.onSurface,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0.15,
    },
    shiftInlineLoading: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      minHeight: 28,
    },
    shiftInlineLoadingText: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    button: {
      backgroundColor: palette.primary,
      borderRadius: 22,
      minHeight: 50,
      paddingVertical: 13,
      paddingHorizontal: 18,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'transparent',
    },
    buttonSecondary: {
      backgroundColor: palette.secondaryButton,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    buttonDisabled: {
      opacity: 0.5,
    },
    buttonText: {
      color: palette.buttonText,
      fontSize: 15,
      fontWeight: '800',
      letterSpacing: 0.15,
    },
    smallText: {
      color: palette.onSurfaceMuted,
      fontSize: 12,
      lineHeight: 18,
    },
    shopModalOverlay: {
      flex: 1,
      backgroundColor: isDark ? 'rgba(0,0,0,0.52)' : 'rgba(18,24,30,0.28)',
      justifyContent: 'center',
      paddingHorizontal: 20,
      paddingVertical: 24,
    },
    shopModalCard: {
      backgroundColor: palette.surfaceRaised,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      borderRadius: 24,
      overflow: 'hidden',
      maxHeight: 420,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 14 },
      shadowOpacity: isDark ? 0.22 : 0.08,
      shadowRadius: 24,
      elevation: 8,
    },
    shopModalTitle: {
      color: palette.onSurface,
      fontSize: 18,
      fontWeight: '800',
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 12,
    },
    shopDropdownScroll: {
      maxHeight: 344,
    },
    shopOptionRow: {
      minHeight: 54,
      paddingHorizontal: 16,
      justifyContent: 'center',
      borderBottomWidth: 1,
      borderBottomColor: palette.outlineVariant,
    },
    shopOptionRowActive: {
      backgroundColor: palette.primaryContainer,
    },
    shopOptionText: {
      color: palette.onSurface,
      fontSize: 15,
      fontWeight: '500',
    },
    shopOptionTextActive: {
      color: palette.primaryStrong,
      fontWeight: '700',
    },
    shopEmptyWrap: {
      paddingHorizontal: 16,
      paddingVertical: 18,
      gap: 12,
    },
    shopEmptyText: {
      color: palette.onSurfaceMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    shopRefreshButton: {
      alignSelf: 'flex-start',
      paddingHorizontal: 14,
    },
    shopSelectTrigger: {
      minHeight: 54,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      backgroundColor: palette.surface,
      paddingHorizontal: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    shopSelectTriggerActive: {
      borderColor: palette.primary,
      backgroundColor: palette.primaryContainer,
    },
    shopSelectTriggerText: {
      color: palette.onSurfaceMuted,
      fontSize: 15,
      fontWeight: '500',
    },
    shopSelectTriggerTextActive: {
      color: palette.onSurface,
      fontWeight: '700',
    },
    shopSelectChevron: {
      color: palette.onSurface,
      fontSize: 15,
      lineHeight: 18,
    },
  })
}

export const lightStyles = createStyles(getAndroidThemePalette(false), false)
export const darkStyles = createStyles(getAndroidThemePalette(true), true)
export const companyStyles = createStyles(getAndroidCompanyPalette(), true)
